version: 2

before:
  hooks:
    - go mod tidy
    - go test ./... -timeout=30s

builds:
  - id: lvt
    main: ./cmd/lvt
    binary: lvt
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: Performance
      regexp: '^perf(\(.+\))?:'
      order: 2
    - title: Documentation
      regexp: '^docs(\(.+\))?:'
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: livefir
    name: livetemplate
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## LiveTemplate {{ .Tag }}

    Release of LiveTemplate framework with synchronized versions across all components:
    - **Go Library**: `github.com/livefir/livetemplate@{{ .Tag }}`
    - **TypeScript Client**: `@livefir/livetemplate-client@{{ trimprefix .Tag "v" }}`
    - **CLI Tool**: `lvt` (binaries below)

    ### Installation

    **Go Library:**
    ```bash
    go get github.com/livefir/livetemplate@{{ .Tag }}
    ```

    **TypeScript Client:**
    ```bash
    npm install @livefir/livetemplate-client@{{ trimprefix .Tag "v" }}
    ```

    **CLI Tool:**
    Download the appropriate binary for your platform from the assets below.
  footer: |
    ---

    **Full Changelog**: https://github.com/livefir/livetemplate/blob/main/CHANGELOG.md

# Homebrew tap (optional - uncomment if you have a tap)
# brews:
#   - name: lvt
#     repository:
#       owner: livefir
#       name: homebrew-tap
#     homepage: https://github.com/livefir/livetemplate
#     description: LiveTemplate CLI - Code generator and development server
#     license: MIT
#     install: |
#       bin.install "lvt"
